AV-68536: complete spring data couchbase quickstart
couchbase-examples/java-springdata-quickstart pull request #34
Opened 2023-12-12 00:29 UTC by teetangh

2024-01-17 10:42 UTC, nithishr requested changes
Only the README has been reviewed. 
Recommendations:
- Move the code explanations into the tutorial on Developer Portal
- Adapt the text to be Capella first. 
- Check the recommendations from spring boot as well.

2024-01-17 10:42 UTC, nithishr commented on README.md
> +- [Java 1.8 or higher](https://www.oracle.com/java/technologies/javase-downloads.html)
Java 1.8 looks suspicious.

2024-01-17 10:42 UTC, nithishr commented on README.md
>  The sample application provides a configuration bean that uses default couchbase login and password:
There is no default couchbase login & password. You need to adapt. 
This entire section needs to be rephrased to be Capella first.

2024-01-17 10:42 UTC, nithishr commented on README.md
> +## Let's Review the Code
This needs to go to the tutorial from the readme

2024-01-17 10:42 UTC, nithishr commented on README.md
>  ## Conclusion
Conclusion is not required as well.

2024-01-31 18:00 UTC, deniswsrosa commented on src/main/java/org/couchbase/quickstart/springdata/models/Airline.java
> +public class Airline implements Serializable {
waaayyyy to many annotations.

2024-01-31 18:00 UTC, deniswsrosa commented on src/main/java/org/couchbase/quickstart/springdata/models/Airport.java
> +@Builder
too many annotations

2024-01-31 18:00 UTC, deniswsrosa commented on src/main/java/org/couchbase/quickstart/springdata/models/Route.java
> +@Builder
same issue here

2024-01-31 18:00 UTC, deniswsrosa commented on src/main/java/org/couchbase/quickstart/springdata/models/Route.java
> +    public static class Schedule implements Serializable {
same issue here

2024-01-31 18:06 UTC, deniswsrosa commented on src/main/java/org/couchbase/quickstart/springdata/repository/AirlineRepository.java
> +    Page<Airline> findAll(Pageable pageable);
Double check that Couchbase repository doesn't provide this method by default.

2024-01-31 18:08 UTC, deniswsrosa commented on src/main/resources/application.properties
>  server.forward-headers-strategy=framework
not sure if this is needed

2024-02-07 04:06 UTC, teetangh commented on README.md
> +Instead of the hash symbols, you need to add the values for the Couchbase connection.
that was for the old readme. updated it

2024-02-07 04:06 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/config/CouchbaseConfiguration.java
> +    // return "couchbases://cb.jnym5s9gv4ealbe.cloud.couchbase.com?tls=no_verify"
this was part of the old code. removed this along with the code.

2024-02-07 04:07 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/config/CouchbaseConfiguration.java
> +      cluster.buckets().createBucket(
removing the code to create a bucket if it doesnt exist just as the other tutorial.

2024-02-07 04:10 UTC, teetangh commented on README.md
>  The sample application provides a configuration bean that uses default couchbase login and password:
removed the phrase as it was unnecessary

2024-02-07 04:12 UTC, teetangh commented on README.md
> +Note: The `-x test` option is used to skip the tests. The tests require the application to be running.
yes this works.

2024-02-07 04:13 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/Application.java
> +@OpenAPIDefinition(info = @Info(title = "Quickstart in Couchbase with Spring Data", version = "2.0", description = "<html><body><h2>A quickstart API using Java and Spring Data with Couchbase and trav
extracted to variables.

2024-02-07 04:13 UTC, teetangh commented on README.md
>  ## Conclusion
removed conclusion

2024-02-07 04:14 UTC, teetangh commented on README.md
> +## Let's Review the Code
migrated from readme to developer tutorial

2024-02-07 04:29 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/repository/AirlineRepository.java
> +    Page<Airline> findAll(Pageable pageable);
it does. But we want the paginated version of this.

2024-02-09 03:07 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/repository/AirlineRepository.java
> +    Page<Airline> findAll(Pageable pageable);
have removed it to use the super method instead

2024-02-09 06:33 UTC, teetangh commented on build.gradle
> +	id 'org.springframework.boot' version '2.7.18'
upgraded everything

2024-02-14 10:23 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/models/Route.java
> +@Builder
trimmed it to a bare minimum of 4

2024-02-14 10:23 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/models/Route.java
> +    public static class Schedule implements Serializable {
trimmed it to a bare minimum of 4

2024-02-14 10:24 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/models/Airport.java
> +@Builder
trimmed it to a bare minimum of 4

2024-02-14 10:25 UTC, teetangh commented on README.md
> +spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
We are actually using this matching routes like airline/{id}.
There are other matchers as well like regex matcher,prefix matcher, full path matcher.

without explicitly mentioning this property, we get the following error:

```
Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null
```

2024-02-15 10:32 UTC, teetangh commented on src/main/resources/application.properties
>  server.forward-headers-strategy=framework
removed it

2024-02-15 10:43 UTC, teetangh commented on README.md
> +server.use-forward-headers=true
removed it

2024-02-15 10:43 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/controller/RouteController.java
> +    @Operation(summary = "Update a route")
added meaningful description to all routes

2024-02-21 09:44 UTC, deniswsrosa requested changes
There are a few adjusments left

2024-02-21 09:44 UTC, deniswsrosa commented on README.md
> +All configuration for communication with the database is read from the environment variables. We have provided a convenience feature in this quickstart to read the environment variables from a local
Specify what are the environment variables the user can specify:
DB_CONN_STR ->
DB_USERNAME ->
DB_PASSWORD ->

2024-02-21 09:44 UTC, deniswsrosa commented on README.md
> +Instead of DB_CONN_STR, DB_USERNAME, and DB_PASSWORD, you should replace these with the connection string, username, and password for your Couchbase cluster. The connection string is the URL of your
this block is a bit confusing, as you ask the placeholders have the same name as the environment variables. The springbood tutorial also has the same problem. A better approach is to say: 

- You can specify your connection using the following environment variables: ....
- Additionally, you can also specify it via properties file:

2024-02-21 09:44 UTC, deniswsrosa commented on README.md
> +spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
remove this  line from the docs, it is irrelevant for what we need to explain

2024-02-21 09:44 UTC, deniswsrosa commented on README.md
> +server.forward-headers-strategy=framework
remove this line for the readme, it is irrelevant

2024-02-21 09:44 UTC, deniswsrosa commented on src/main/java/org/couchbase/quickstart/springdata/models/RestResponsePage.java
> +    public RestResponsePage(List<T> content, Pageable pageable, long total) {
not used anywhere

2024-02-21 09:44 UTC, deniswsrosa commented on src/main/java/org/couchbase/quickstart/springdata/models/RestResponsePage.java
> +    public RestResponsePage(List<T> content) {
not used anywhere

2024-02-21 09:44 UTC, deniswsrosa commented on src/main/java/org/couchbase/quickstart/springdata/models/RestResponsePage.java
> +    public RestResponsePage() {
not used anywhere

2024-02-21 09:44 UTC, deniswsrosa commented on README.md
> +- Create the new entity (collection) in the Couchbase bucket. You can create the collection using the [SDK](https://docs.couchbase.com/sdk-api/couchbase-java-client-3.5.2/com/couchbase/client/java/Co
- Create the collection is the step one, create the entity is another step,
- You are not mentioning about the need of creating a new entity in the models package. I assume that the same error is present on the spring boot tutorial. Please fix both.

2024-02-21 09:44 UTC, deniswsrosa commented on README.md
> +- Define the routes in a new file in the `controllers` folder similar to the existing routes like `AirportController.java`.
Define a new Controller in the `controllers` package similar to existing classes like `AirportController.java`. (you also need to adjust the phrase bellow as well)

2024-02-23 08:11 UTC, teetangh commented on README.md
> +- Create the new entity (collection) in the Couchbase bucket. You can create the collection using the [SDK](https://docs.couchbase.com/sdk-api/couchbase-java-client-3.5.2/com/couchbase/client/java/Co
done.

2024-02-23 08:12 UTC, teetangh commented on README.md
> +- Define the routes in a new file in the `controllers` folder similar to the existing routes like `AirportController.java`.
done

2024-02-23 08:12 UTC, teetangh commented on README.md
> +server.forward-headers-strategy=framework
removed

2024-02-23 08:12 UTC, teetangh commented on README.md
> +spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
removed

2024-02-23 08:12 UTC, teetangh commented on README.md
> +2. How to write simple parametrized [N1QL queries](https://docs.couchbase.com/java-sdk/current/howtos/n1ql-queries-with-sdk.html) using the built-in travel-sample bucket.
changed

2024-02-23 08:17 UTC, teetangh commented on README.md
> +- Gradle
done

2024-02-23 08:18 UTC, teetangh commented on README.md
> +  - [Load travel-sample bucket in Couchbase Capella](https://docs.couchbase.com/cloud/clusters/data-service/import-data-documents.html#import-sample-data)
hopefully this is better

2024-02-23 08:24 UTC, teetangh commented on README.md
> +Instead of DB_CONN_STR, DB_USERNAME, and DB_PASSWORD, you should replace these with the connection string, username, and password for your Couchbase cluster. The connection string is the URL of your
done

2024-02-23 08:24 UTC, teetangh commented on README.md
> +All configuration for communication with the database is read from the environment variables. We have provided a convenience feature in this quickstart to read the environment variables from a local
done

2024-02-23 09:50 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/models/RestResponsePage.java
> +    public RestResponsePage() {
removed

2024-02-23 09:50 UTC, teetangh commented on src/main/java/org/couchbase/quickstart/springdata/models/RestResponsePage.java
> +    public RestResponsePage(List<T> content, Pageable pageable, long total) {
removed

2024-02-26 10:21 UTC, deniswsrosa approved these changes

2024-02-26 10:21 UTC, merged